# Generated by Django 5.1.3 on 2024-12-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('code_adh', models.AutoField(primary_key=True, serialize=False)),
                ('nom_adh', models.CharField(max_length=100)),
                ('nbr_emprunts_adh', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('code_auteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_auteur', models.CharField(max_length=100)),
                ('prenom_auteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('code_livre', models.AutoField(primary_key=True, serialize=False)),
                ('titre_livre', models.CharField(max_length=200)),
                ('nbre_page', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='livres/')),
                ('disponibilite', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='Livres.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField()),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='Livres.adherent')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='Livres.livre')),
            ],
        ),
    ]
