# Generated by Django 5.1.3 on 2024-12-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0002_adherent_auteur_livre_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
