# Generated by Django 5.1.3 on 2024-12-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0003_livre_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='exemplaires_disponibles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livre',
            name='total_exemplaires',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
