# Generated by Django 5.1.3 on 2024-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0005_adherent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auteurs/'),
        ),
    ]
