# Generated by Django 5.1.3 on 2024-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0007_alter_livre_exemplaires_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_retour_effective',
            field=models.DateField(blank=True, null=True),
        ),
    ]
